// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_REMOVED',
    appId: '1:102779249462:web:0dbbd91a1eba05e8858997',
    messagingSenderId: '102779249462',
    projectId: 'granith-skyforge',
    authDomain: 'granith-skyforge.firebaseapp.com',
    storageBucket: 'granith-skyforge.firebasestorage.app',
    measurementId: 'G-W72ZPQB0H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_REMOVED',
    appId: '1:102779249462:android:7afb7e88efb7179f858997',
    messagingSenderId: '102779249462',
    projectId: 'granith-skyforge',
    storageBucket: 'granith-skyforge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_REMOVED',
    appId: '1:102779249462:ios:e8b5690a530980cf858997',
    messagingSenderId: '102779249462',
    projectId: 'granith-skyforge',
    storageBucket: 'granith-skyforge.firebasestorage.app',
    iosBundleId: 'com.example.projectGranith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_REMOVED',
    appId: '1:102779249462:ios:e8b5690a530980cf858997',
    messagingSenderId: '102779249462',
    projectId: 'granith-skyforge',
    storageBucket: 'granith-skyforge.firebasestorage.app',
    iosBundleId: 'com.example.projectGranith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_REMOVED',
    appId: '1:102779249462:web:b071d4d2c9ff2428858997',
    messagingSenderId: '102779249462',
    projectId: 'granith-skyforge',
    authDomain: 'granith-skyforge.firebaseapp.com',
    storageBucket: 'granith-skyforge.firebasestorage.app',
    measurementId: 'G-43GRXT23QV',
  );
}
