-- Usage snapshots are generated by the Edge Function with service_role.
-- Authenticated users with billing/infra/settings permissions may read them,
-- but must not be able to forge or delete snapshots through PostgREST.

drop policy if exists usage_stats_manage_authorized on public.usage_stats;

revoke insert, update, delete on public.usage_stats from authenticated;
grant select on public.usage_stats to authenticated;
grant select, insert, update, delete on public.usage_stats to service_role;
